# Homework: Introduction to Python

## Problem 1: Containers and Functions

**(a)** Write a function called `unique_sorted` that takes a list of integers and returns a **new** list containing the unique values in ascending order. For example, `unique_sorted([3, 1, 2, 3, 2])` should return `[1, 2, 3]`.

In [18]:
def unique_sorted(values):
    return sorted(set(values))

In [20]:
unique_sorted([3, 1, 2, 3, 2])  # Expected output: [1, 2, 3]

[1, 2, 3]

**(b)** Write a function called `count_words` that takes a list of strings and returns a dictionary mapping each word (lowercased) to its count. For example, `count_words(["Apple", "banana", "apple", "BANANA"])` should return `{'apple': 2, 'banana': 2}`.

In [27]:
def count_words(words):
    lower_words = [w.lower() for w in words]
    words_count = {}
    for w in lower_words:
        if w in words_count:
            words_count[w] += 1
        else:
            words_count[w] = 1
    return words_count

In [28]:
count_words(["Apple", "banana", "apple", "BANANA"]) # Expected output: {'apple': 2, 'banana': 2}

{'apple': 2, 'banana': 2}

**(c)** You are given a list of `(name, score)` tuples. Write a function called `average_scores` that returns a dictionary mapping each name to their average score. If a name appears multiple times, you should average all of their scores. For example, `average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)])` should return `{'Ada': 95.0, 'Bob': 80.0}`.

In [33]:
def average_scores(records):
    total_scores = {}
    name_counts = {}
    for name, score in records:
        if name in total_scores:
            total_scores[name] += score
            name_counts[name] += 1
        else:
            total_scores[name] = score
            name_counts[name] = 1
    average_scores = {name: total_scores[name] / name_counts[name] for name in total_scores}
    return average_scores


In [34]:
average_scores([("Ada", 90), ("Bob", 80), ("Ada", 100)])

{'Ada': 95.0, 'Bob': 80.0}

## Problem 2: Writing Functions with Comprehensions

**(a)** Write a function called `filter_by_threshold` that takes a list of numbers and a threshold value, and returns a new list containing only the numbers greater than the threshold. Use a list comprehension. For example, `filter_by_threshold([1, 5, 3, 8, 2], 3)` should return `[5, 8]`.

In [31]:
def filter_by_threshold(numbers, threshold):
    numbers_filtered = [num for num in numbers if num > threshold]
    return numbers_filtered

In [32]:
filter_by_threshold([1, 5, 3, 8, 2], 3)

[5, 8]

**(b)** Write a function called `word_lengths` that takes a list of strings and returns a dictionary mapping each unique word to its length. Use a dictionary comprehension. For example, `word_lengths(["hello", "world", "hi"])` should return `{'hello': 5, 'world': 5, 'hi': 2}`.

In [35]:
def word_lengths(words):
    return {word: len(word) for word in words}

In [36]:
word_lengths(["hello", "world", "hi"])

{'hello': 5, 'world': 5, 'hi': 2}

**(c)** Write a function called `common_elements` that takes two lists and returns a set of elements that appear in both lists. Use a set comprehension. For example, `common_elements([1, 2, 3, 4], [3, 4, 5, 6])` should return `{3, 4}`.

In [1]:
def common_elements(list1, list2):
    intersection = [x for x in list1 if x in list2]
    return set(intersection) # remove duplicates

In [2]:
common_elements([1, 2, 3, 4], [3, 4, 5, 6])

{3, 4}

## Problem 3: NumPy Array Operations

**(a)** Given the following 2D array, write NumPy code to:
1. Extract the second row as a 1D array
2. Extract the last column as a 2D column vector (shape should be `(4, 1)`)
3. Extract the 2x2 subarray from the bottom-right corner

In [43]:
import numpy as np

data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

In [84]:
# 1. Extract the second row as a 1D array
data[1]

array([5, 6, 7, 8])

In [ ]:
# Extract the last column as a 2D array
data[:, -1:]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [58]:
# Extract the 2x2 subarray from the bottom-right corner
data[-2:, -2:]

array([[11, 12],
       [15, 16]])

**(b)** Without using loops, write NumPy code to:
1. Create a 5x5 array where each element is the sum of its row and column indices (i.e., element at position `[i, j]` should equal `i + j`)
2. Normalize each row of a matrix so that each row sums to 1 (use broadcasting)

In [76]:
# part 1
rows = np.arange(5)
cols = np.arange(5).reshape(5, 1)
rows + cols

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [73]:
# Given matrix for part 2
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=float)

matrix/np.sum(matrix, axis=1).reshape(-1, 1)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.29166667, 0.33333333, 0.375     ]])

**(c)** Explain the difference between the following two indexing operations. What are the shapes of `a` and `b`? Which one creates a view and which creates a copy?

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = arr[0:1, :]
b = arr[[0], :]

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [75]:
print(a)
print(b)

[[1 2 3]]
[[1 2 3]]


Both `a` and `b` have shape `(1, 3)`.

`a` is a slice, so it creates a view.
`b` uses a list of indices,so it creates a copy.

## Problem 4: Improving Inefficient Code

The following code computes pairwise distances between points but is inefficient. Rewrite it using NumPy broadcasting to eliminate the nested loops. Your solution should produce the same result as the original code.

In [85]:
import numpy as np

def pairwise_distances_slow(points):
    """Compute pairwise Euclidean distances between points.

    Parameters
    ----------
    points : np.ndarray
        Array of shape (n, d) where n is number of points and d is dimensions.

    Returns
    -------
    np.ndarray
        Array of shape (n, n) containing pairwise distances.
    """
    n = points.shape[0]
    distances = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            diff = points[i] - points[j]
            distances[i, j] = np.sqrt(np.sum(diff ** 2))
    return distances

In [ ]:
import numpy as np

def pairwise_distances_fast(points):
    diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
    distances = np.sqrt(np.sum(diff ** 2, axis=-1))
    return distances

In [87]:
points = np.array([[0, 0], [1, 0], [0, 1]])
pairwise_distances_slow(points)


array([[0.        , 1.        , 1.        ],
       [1.        , 0.        , 1.41421356],
       [1.        , 1.41421356, 0.        ]])

In [88]:
pairwise_distances_fast(points)

array([[0.        , 1.        , 1.        ],
       [1.        , 0.        , 1.41421356],
       [1.        , 1.41421356, 0.        ]])

## Problem 5: The View Trap

A colleague wrote the following function to standardize columns of a matrix (subtract mean, divide by standard deviation). However, users are reporting unexpected behavior.

In [96]:
import numpy as np

def standardize_columns(data):
    """Standardize each column to have mean 0 and std 1."""
    result = data
    for j in range(data.shape[1]):
        col = result[:, j]
        col_mean = np.mean(col)
        col_std = np.std(col)
        col = (col - col_mean) / col_std
    return result

**(a)** Explain why this function does not work as intended. What fundamental concept about NumPy arrays is being misunderstood?

In [97]:
standardize_columns(np.array([[1, 2], [3, 4]]))

array([[1, 2],
       [3, 4]])

`col` is a view, but `col = (col - col_mean) / col_std` makes a copy.

**(b)** A user runs the following code and is surprised by the output. Explain what happens and why.

In [93]:
original = np.array([[1.0, 2.0], [3.0, 4.0]])
normalized = standardize_columns(original)
print("Original:", original)
print("Normalized:", normalized)
print("Are they the same object?", original is normalized)

Original: [[1. 2.]
 [3. 4.]]
Normalized: [[1. 2.]
 [3. 4.]]
Are they the same object? True


As is explained in part **(a)**, `col` becomes a copy. Although `col` is normalized, `result` isn't normalized. Since `result = data`, the output (`result`) is exactly the same as the input (`data`).

**(c)** Rewrite the function correctly. Your solution should actually standardize the columns, not modify the input array, and use vectorized operations instead of explicit loops where possible.


In [5]:
import numpy as np

def standardize_columns_v2(data):
    """Standardize each column to have mean 0 and std 1."""
    result = data
    col_mean = np.mean(result, axis=0)
    col_std = np.std(result, axis=0)
    result = (result - col_mean) / col_std
    return result


**(d)** Write a simple test that verifies your corrected function works properly. The test should check that the output columns have approximately mean 0 and standard deviation 1.

In [4]:
orig_data = np.array([[1, 2, 3], [4, 5, 6]])
normalized_data = standardize_columns_v2(orig_data)
normalized_data

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [105]:
np.mean(normalized_data, axis=0), np.std(normalized_data, axis=0)

(array([0., 0., 0.]), array([1., 1., 1.]))

In [ ]:
# Write a test for standardize_columns_v2

def test_standardize_columns_v2():
    data = np.array([[1, 2], [3, 4], [5, 6]])
    normalized = standardize_columns_v2(data)
    means = np.mean(normalized, axis=0)
    stds = np.std(normalized, axis=0)
    assert np.allclose(means, 0), "Means are not close to 0"
    assert np.allclose(stds, 1), "Standard deviations are not close to 1"
    print("All tests passed!")

In [6]:
test_standardize_columns_v2()

All tests passed!
